apiVersion: v1
kind: Service
metadata:
  name: postgres  # ⚠ Ce nom DOIT être "postgres" pour correspondre à l'URL utilisée
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
