apiVersion: apps/v1
kind: Deployment
metadata:
  name: salle-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salle-service
  template:
    metadata:
      labels:
        app: salle-service
    spec:
      containers:
      - name: salle-service
        image: oumaimansir/salle_service:v2
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://myuser:123456@postgres:5432/authdb"
        - name: KAFKA_BROKER
          value: "kafka:9092"
